all: 
	/usr/bin/g++ rsatest.cpp -std=c++17 -lcryptopp -o rsatest
	/usr/bin/g++ hashtest.cpp -std=c++17 -lcryptopp -o hashtest
	/usr/bin/g++ signaturetest.cpp -std=c++17 -lcryptopp -o signaturetest
	/usr/bin/g++ ecGenKeyPair.cpp -std=c++17 -lcryptopp -o ecGenKeyPair
	/usr/bin/g++ ecctest2.cpp -std=c++17 -lcryptopp -o ecctest2
	/usr/bin/g++ maptest.cpp -std=c++17 -lcryptopp -o maptest
	/usr/bin/g++ -std=c++17 -O2 -Wall -pedantic -pthread jsonSerialization.cpp -o jsonSerialize
	/usr/bin/g++ -std=c++17 -O2 -Wall -pedantic -pthread boostserial.cpp -o boostserial
	/usr/bin/g++ jsontest.cpp -I ../include -std=c++17 -o jsontest
	/usr/bin/g++ vector.cpp -std=c++17 -o vector
	/usr/bin/g++ vectormap.cpp -std=c++17 -o vectormap
	/usr/bin/g++ -Wall -std=c++17 template.cpp -o template
